package Library;


/**
* Library/_LibImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Library.idl
* Wednesday, March 28, 2018 10:45:13 PM IST
*/

public abstract class _LibImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Library.Lib, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _LibImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("issue_book", new java.lang.Integer (0));
    _methods.put ("return_book", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Library/Lib/issue_book
       {
         String b_name = in.read_string ();
         boolean $result = false;
         $result = this.issue_book (b_name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Library/Lib/return_book
       {
         String b_name = in.read_string ();
         boolean $result = false;
         $result = this.return_book (b_name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Library/Lib:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _LibImplBase
