package Library;


/**
* Library/Lib.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Library.idl
* Wednesday, March 28, 2018 10:45:13 PM IST
*/

public interface Lib extends LibOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Lib
