package Library;

/**
* Library/LibHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Library.idl
* Wednesday, March 28, 2018 10:45:13 PM IST
*/

public final class LibHolder implements org.omg.CORBA.portable.Streamable
{
  public Library.Lib value = null;

  public LibHolder ()
  {
  }

  public LibHolder (Library.Lib initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Library.LibHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Library.LibHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Library.LibHelper.type ();
  }

}
