package Library;


/**
* Library/LibOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Library.idl
* Wednesday, March 28, 2018 10:45:13 PM IST
*/

public interface LibOperations 
{
  boolean issue_book (String b_name);
  boolean return_book (String b_name);
} // interface LibOperations
